name: df_detection
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib==3.8.4
  - tqdm==4.66.4
  - opencv==4.9.0
  - pillow==10.3.0
  - face-recognition==1.3.0
  - click==8.1.7
  - dlib==19.24.4
  - scipy
  - numpy==1.26.4
  - python-dotenv
  - pydantic
  - colorlog
  - scikit-learn
  - multiprocess
  - psutil
  - pip
  - pip:
      - colorlog==6.8.2
      - face-recognition==1.3.0
      - flake8==7.1.1
      - mediapipe==0.10.14
      - mtcnn==0.1.1
      - multiprocess==0.70.16
      - opencv-python-headless==4.9.0
      - pip==24.0
      - psutil==6.0.0
      - pydantic==2.5.3
      - PySocks==1.7.1
      - python-dotenv==1.0.1
      - retina-face==0.0.17
      - scikit-learn==1.5.1
      - tf_keras==2.16.0
      - tornado==6.4.1
      - unicodedata2==15.1.0
